name: Laravel CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  # ==========================================================
  # TESTS
  # ==========================================================

  tests:
    name: Tests Laravel

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d testing"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:

      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: testing
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: Installer Composer
        run: |
          composer install \
            --no-interaction \
            --prefer-dist

      - name: Préparer Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Nettoyer la configuration
        run: |
          php artisan config:clear

      - name: Vérifier PostgreSQL
        run: |
          pg_isready \
            -h 127.0.0.1 \
            -p 5432 \
            -U postgres

      - name: Préparer la base
        run: |
          php artisan migrate:fresh --force

      - name: Test unitaire
        run: |
          php artisan test


  # ==========================================================
  # QUALITY
  # ==========================================================

  quality:
    name: Quality Gate

    runs-on: ubuntu-latest

    needs: tests

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none

      - name: Installer Composer
        run: |
          composer install \
            --no-interaction \
            --prefer-dist

      - name: Vérifier Pint
        run: |
          ./vendor/bin/pint
      
      - name: Les modification apportées
        run: git status

      - name: Les corrections
        run: git diff

      - name: Le test pin vérification
        run: |
          ./vendor/bin/pint --test

      - name: Installer PHPStan et Larastan
        run: |
          mkdir -p tools
          composer require --working-dir=tools phpstan/phpstan larastan/larastan

      - name: PHPStan
        run: ./tools/vendor/bin/phpstan analyse app     
  build:
    name: Build Docker

    runs-on: ubuntu-latest

    needs:
      - tests
      - quality

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Vérifier Docker
        run: |
          docker --version

      - name: Construire l'image
        run: |
          docker build \
            -f docker/php/Dockerfile \
            -t task-app:${{ github.sha }} \
            .

      - name: Vérifier l'image
        run: |
          docker image inspect \
            task-app:${{ github.sha }}


